

import Link from "next/link";
import Image from "next/image";

import logoImg from "@/assets/logo.png";
import classes from "./main-header.module.css";
import MainHeaderBackground from "./main-header-background";
import NavLink from "./nav-link";


export default function MainHeader() {
 
  return (
    <>
      <MainHeaderBackground />
      <header className={classes.header}>
        <Link className={classes.logo} href="/">
          {/* <img src={logoImg.src} alt="A plate with food on it"/> */}
          <Image src={logoImg} alt="A plate with food on it" priority />
          {/* because this object that is generated by nextjs when you import an image like this, contains useful information that's used under the hood by this image component to display it in an optimised way. for example it automatically detects the size of this image*/}
          {/* Add the priority property to this image since it will always be visible when this page loads, so lazy loading doesn't make alot of sense here and we wanna tell nextjs and the browser that this image will always be loaded as quickly as possible to make sure we dont get unnecessary content shift or flikering when the page loads*/}
          NextLevel Food
        </Link>

        <nav className={classes.nav}>
          <ul>
            <li>
              <NavLink href="/meals">Browse Meals</NavLink>
            </li>
            <li>
              <NavLink href="/community">Foodies Community</NavLink>
            </li>
          </ul>
        </nav>
      </header>
    </>
  );
}
